### ISSUE TITLE
Weird segfault with metatable use

### ISSUE THREAD

**Issue by philipdexter** [scizzorz/rain#45]
```
import array


main = func()
  let a = table from array
  a[0] = 1
  a[1] = 2

  let double = func(x) -> x * 2

  let cp = func(a)
    let ret = table from a.metatable
    return ret

  array.map(cp(table from array), double)
  print("got here")
  array.map(cp(table), double)


```

The first `array.map` won't crash, but the second one does.

Removing the `from array` in the definition of `a` has no effect.

If I remove the `from a.metatable` from the first line of `cp` then neither crash.

**Comment by scizzorz** [comment]
Happens when `x.metatable` isn't a table of some sort. In `lib/array.rn` it does something like `table from x.metatable` which isn't actually safe - just realized it. If `x` has no metatable, then `x.metatable` returns `null` which then sets the new table's metatable to `null`, which causes this seg fault.
